// app/utils/db.helpers.server.js
import prisma from "../db.server";

export const DEFAULT_TEMPLATES = [
  // FREE TEMPLATES (3)
  {
    id: "template-1",
    name: "Cyan Neon Glow",
    plan: "FREE",
    description: "Sleek dark mode banner with vibrant cyan text and star accents.",
    settings: JSON.stringify({
      messages: ["⚡ FREE SHIPPING OVER $50", "🎁 15% OFF YOUR FIRST ORDER", "🚀 FAST 2-DAY DELIVERY"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: "1px",
      textTransform: "uppercase",
      backgroundColor: "#0D1117",
      textColor: "#19D8CF",
      hoverColor: "#0FB5AD",
      borderColor: "#19D8CF",
      height: 42,
      topPadding: 10,
      bottomPadding: 10,
      dividerIcon: "✦",
      dividerColor: "#19D8CF",
      hasCta: false,
    }),
  },
  {
    id: "template-2",
    name: "Minimal Monochrome",
    plan: "FREE",
    description: "Clean and minimalist black & white store announcement bar.",
    settings: JSON.stringify({
      messages: ["NEW SEASON ARRIVALS NOW LIVE", "COMPLIMENTARY RETURNS WORLDWIDE", "SUSTAINABLE PACKAGING"],
      direction: "Right to Left",
      speed: "Slow",
      fontFamily: "Inter",
      fontSize: 13,
      fontWeight: "600",
      letterSpacing: "2px",
      textTransform: "uppercase",
      backgroundColor: "#18181B",
      textColor: "#FAFAFA",
      hoverColor: "#27272A",
      borderColor: "#3F3F46",
      height: 40,
      topPadding: 9,
      bottomPadding: 9,
      dividerIcon: "|",
      dividerColor: "#71717A",
      hasCta: false,
    }),
  },
  {
    id: "template-3",
    name: "Sunset Coral Flash",
    plan: "FREE",
    description: "High-contrast energetic coral banner for flash announcements.",
    settings: JSON.stringify({
      messages: ["🔥 FLASH SALE: UP TO 40% OFF", "USE CODE: SUNSET40", "FREE GIFT WITH ORDERS OVER $80"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: "1px",
      textTransform: "uppercase",
      backgroundColor: "#FF5A5F",
      textColor: "#FFFFFF",
      hoverColor: "#E0484C",
      borderColor: "#FF5A5F",
      height: 44,
      topPadding: 10,
      bottomPadding: 10,
      dividerIcon: "★",
      dividerColor: "#FFFFFF",
      hasCta: false,
    }),
  },

  // BASIC TEMPLATES (4)
  {
    id: "template-4",
    name: "Crimson Fire Sale",
    plan: "BASIC",
    description: "Bold red promo banner with star icons and vibrant text.",
    settings: JSON.stringify({
      messages: ["🔥 BIG WEEKEND SALE IS LIVE", "SAVE UP TO 50% STOREWIDE", "CODE: FIRE50 AT CHECKOUT"],
      direction: "Right to Left",
      speed: "Fast",
      fontFamily: "Inter",
      fontSize: 15,
      fontWeight: "800",
      letterSpacing: "1.2px",
      textTransform: "uppercase",
      backgroundColor: "#DC2626",
      textColor: "#FFFFFF",
      hoverColor: "#B91C1C",
      borderColor: "#DC2626",
      height: 46,
      topPadding: 11,
      bottomPadding: 11,
      dividerIcon: "⭐",
      dividerColor: "#FDE047",
      hasCta: false,
    }),
  },
  {
    id: "template-5",
    name: "Ocean Breeze Navy",
    plan: "BASIC",
    description: "Deep sky navy bar with electric blue highlights and lightning dividers.",
    settings: JSON.stringify({
      messages: ["🌊 SUMMER ESSENTIALS COLLECTION", "FREE SHIPPING OVER $75", "30-DAY MONEY BACK GUARANTEE"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: "1.5px",
      textTransform: "uppercase",
      backgroundColor: "#0F172A",
      textColor: "#38BDF8",
      hoverColor: "#1E293B",
      borderColor: "#334155",
      height: 44,
      topPadding: 10,
      bottomPadding: 10,
      dividerIcon: "⚡",
      dividerColor: "#38BDF8",
      hasCta: false,
    }),
  },
  {
    id: "template-6",
    name: "Emerald Eco Organic",
    plan: "BASIC",
    description: "Organic forest green banner designed for eco-friendly brands.",
    settings: JSON.stringify({
      messages: ["🌱 100% ETHICALLY MADE & SUSTAINABLE", "1 PLANT PLANTED FOR EVERY ORDER", "FREE RECYCLABLE PACKAGING"],
      direction: "Right to Left",
      speed: "Slow",
      fontFamily: "Inter",
      fontSize: 13,
      fontWeight: "600",
      letterSpacing: "1px",
      textTransform: "uppercase",
      backgroundColor: "#065F46",
      textColor: "#A7F3D0",
      hoverColor: "#047857",
      borderColor: "#065F46",
      height: 42,
      topPadding: 10,
      bottomPadding: 10,
      dividerIcon: "🌿",
      dividerColor: "#A7F3D0",
      hasCta: false,
    }),
  },
  {
    id: "template-7",
    name: "Electric Violet Spark",
    plan: "BASIC",
    description: "Vibrant indigo-violet marquee with sparkling divider icons.",
    settings: JSON.stringify({
      messages: ["✨ EXCLUSIVE ONLINE DROPS", "BUY 2 GET 1 FREE ON SELECT ITEMS", "JOIN VIP REWARDS TODAY"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: "1.2px",
      textTransform: "uppercase",
      backgroundColor: "#4C1D95",
      textColor: "#DDD6FE",
      hoverColor: "#5B21B6",
      borderColor: "#6D28D9",
      height: 44,
      topPadding: 10,
      bottomPadding: 10,
      dividerIcon: "✨",
      dividerColor: "#F472B6",
      hasCta: false,
    }),
  },

  // PREMIUM TEMPLATES (5)
  {
    id: "template-8",
    name: "Aurora Cyber Gradient",
    plan: "PREMIUM",
    description: "Multi-color neon gradient background with interactive Call-To-Action button.",
    settings: JSON.stringify({
      messages: ["🔥 ULTIMATE TECH & GEAR SALE", "UP TO 50% OFF POPULAR ITEMS", "EXPRESS SAME-DAY DISPATCH"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: "1px",
      textTransform: "uppercase",
      backgroundColor: "linear-gradient(135deg, #7C3AED 0%, #2563EB 50%, #06B6D4 100%)",
      textColor: "#FFFFFF",
      hoverColor: "#6D28D9",
      borderColor: "#7C3AED",
      height: 48,
      topPadding: 12,
      bottomPadding: 12,
      dividerIcon: "⚡",
      dividerColor: "#06B6D4",
      hasCta: true,
      ctaText: "SHOP NOW",
      ctaUrl: "/collections/all",
      ctaBg: "#FFFFFF",
      ctaColor: "#7C3AED",
      ctaRadius: 6,
    }),
  },
  {
    id: "template-9",
    name: "Obsidian Gold Luxury",
    plan: "PREMIUM",
    description: "High-end luxury black and metallic gold banner with CTA button.",
    settings: JSON.stringify({
      messages: ["✦ HAUTE COUTURE 2026 COLLECTION", "HANDCRAFTED LIMITED EDITIONS", "COMPLIMENTARY LUXURY GIFT BOX"],
      direction: "Right to Left",
      speed: "Slow",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: "3px",
      textTransform: "uppercase",
      backgroundColor: "#09090B",
      textColor: "#FDE047",
      hoverColor: "#18181B",
      borderColor: "#27272A",
      height: 46,
      topPadding: 11,
      bottomPadding: 11,
      dividerIcon: "✦",
      dividerColor: "#FDE047",
      hasCta: true,
      ctaText: "EXPLORE",
      ctaUrl: "/collections/luxury",
      ctaBg: "#FDE047",
      ctaColor: "#09090B",
      ctaRadius: 4,
    }),
  },
  {
    id: "template-10",
    name: "Emerald Gold VIP",
    plan: "PREMIUM",
    description: "Deep emerald gradient with gold accents and member CTA button.",
    settings: JSON.stringify({
      messages: ["👑 VIP CLUB EXCLUSIVE DEAL", "EXTRA 20% OFF FOR MEMBERS", "USE CODE: VIPGOLD AT CHECKOUT"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: "1.5px",
      textTransform: "uppercase",
      backgroundColor: "linear-gradient(90deg, #059669 0%, #047857 50%, #064E3B 100%)",
      textColor: "#FEF08A",
      hoverColor: "#047857",
      borderColor: "#059669",
      height: 48,
      topPadding: 12,
      bottomPadding: 12,
      dividerIcon: "👑",
      dividerColor: "#FEF08A",
      hasCta: true,
      ctaText: "CLAIM VIP PERK",
      ctaUrl: "/pages/vip",
      ctaBg: "#FEF08A",
      ctaColor: "#064E3B",
      ctaRadius: 8,
    }),
  },
  {
    id: "template-11",
    name: "Rose Gold Elegance",
    plan: "PREMIUM",
    description: "Chic rose gold pink gradient banner with contrast dark CTA button.",
    settings: JSON.stringify({
      messages: ["💎 NEW FINE JEWELRY & WATCHES", "FREE EXPRESS INSURED SHIPPING", "LIFETIME WARRANTY INCLUDED"],
      direction: "Right to Left",
      speed: "Normal",
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: "1.5px",
      textTransform: "uppercase",
      backgroundColor: "linear-gradient(135deg, #E11D48 0%, #FB7185 50%, #FDA4AF 100%)",
      textColor: "#FFFFFF",
      hoverColor: "#BE123C",
      borderColor: "#E11D48",
      height: 46,
      topPadding: 11,
      bottomPadding: 11,
      dividerIcon: "💎",
      dividerColor: "#FFFFFF",
      hasCta: true,
      ctaText: "DISCOVER NOW",
      ctaUrl: "/collections/jewelry",
      ctaBg: "#111827",
      ctaColor: "#FFFFFF",
      ctaRadius: 8,
    }),
  },
  {
    id: "template-12",
    name: "Midnight Pulsar Glow",
    plan: "PREMIUM",
    description: "Futuristic dark violet to indigo gradient with neon cyan CTA button.",
    settings: JSON.stringify({
      messages: ["🚀 MIDNIGHT DROP IS LIVE", "EXCLUSIVE EARLY ACCESS FOR TODAY ONLY", "LIMITED STOCK AVAILABLE"],
      direction: "Right to Left",
      speed: "Fast",
      fontFamily: "Inter",
      fontSize: 15,
      fontWeight: "800",
      letterSpacing: "2px",
      textTransform: "uppercase",
      backgroundColor: "linear-gradient(90deg, #1E1B4B 0%, #312E81 50%, #4C1D95 100%)",
      textColor: "#22D3EE",
      hoverColor: "#312E81",
      borderColor: "#4C1D95",
      height: 50,
      topPadding: 13,
      bottomPadding: 13,
      dividerIcon: "🔥",
      dividerColor: "#F59E0B",
      hasCta: true,
      ctaText: "GET DEAL",
      ctaUrl: "/collections/deals",
      ctaBg: "#22D3EE",
      ctaColor: "#1E1B4B",
      ctaRadius: 8,
    }),
  },
];

export async function seedTemplatesIfEmpty() {
  for (const t of DEFAULT_TEMPLATES) {
    await prisma.template.upsert({
      where: { id: t.id },
      update: {
        name: t.name,
        plan: t.plan,
        description: t.description,
        settings: t.settings,
      },
      create: t,
    });
  }
}

export async function getShopData(shopDomain) {
  let shop = await prisma.shop.findUnique({ where: { shopDomain } });
  if (!shop) {
    shop = await prisma.shop.create({
      data: {
        shopDomain,
        plan: "BASIC",
      },
    });
  }
  return shop;
}

export async function getBanners(shopDomain) {
  let banners = await prisma.banner.findMany({
    where: { shopDomain },
    orderBy: { updatedAt: "desc" },
  });

  if (banners.length === 0) {
    // Seed initial demo banners matching prompt specs
    const sampleBanners = [
      {
        name: "Free Shipping Banner",
        templateId: "template-1",
        status: "ACTIVE",
        settings: JSON.stringify({
          messages: ["FREE SHIPPING OVER $50", "20% OFF YOUR FIRST ORDER", "SHOP NOW"],
          direction: "Right to Left",
          speed: "Normal",
          fontFamily: "Inter",
          fontSize: 14,
          fontWeight: "600",
          letterSpacing: "1px",
          textTransform: "uppercase",
          backgroundColor: "#19D8CF",
          textColor: "#111827",
          hoverColor: "#0FB5AD",
          borderColor: "#19D8CF",
          height: 42,
          topPadding: 10,
          bottomPadding: 10,
          dividerIcon: "•",
          dividerColor: "#111827",
          hasCta: false,
        }),
      },
      {
        name: "Summer Sale Banner",
        templateId: "template-2",
        status: "PAUSED",
        settings: JSON.stringify({
          messages: ["🔥 SUMMER SALE", "20% OFF TODAY", "USE CODE: SUMMER20"],
          direction: "Left to Right",
          speed: "Normal",
          fontFamily: "Inter",
          fontSize: 15,
          fontWeight: "700",
          letterSpacing: "1px",
          textTransform: "uppercase",
          backgroundColor: "#FF5B5B",
          textColor: "#FFFFFF",
          hoverColor: "#E04848",
          borderColor: "#FF5B5B",
          height: 44,
          topPadding: 10,
          bottomPadding: 10,
          dividerIcon: "★",
          dividerColor: "#FFFFFF",
          hasCta: false,
        }),
      },
      {
        name: "Collection Banner",
        templateId: "template-3",
        status: "PAUSED",
        settings: JSON.stringify({
          messages: ["NEW COLLECTION AVAILABLE", "EXPLORE LATEST TRENDS"],
          direction: "Right to Left",
          speed: "Slow",
          fontFamily: "Inter",
          fontSize: 14,
          fontWeight: "600",
          letterSpacing: "1.5px",
          textTransform: "uppercase",
          backgroundColor: "#172554",
          textColor: "#FFFFFF",
          hoverColor: "#1E3A8A",
          borderColor: "#172554",
          height: 44,
          topPadding: 10,
          bottomPadding: 10,
          dividerIcon: "⚡",
          dividerColor: "#3B82F6",
          hasCta: false,
        }),
      },
      {
        name: "Offer Banner",
        templateId: "template-4",
        status: "DRAFT",
        settings: JSON.stringify({
          messages: ["LIMITED TIME OFFER", "GET 15% CASHBACK ON ALL ORDERS"],
          direction: "Left to Right",
          speed: "Normal",
          fontFamily: "Inter",
          fontSize: 13,
          fontWeight: "500",
          letterSpacing: "2px",
          textTransform: "uppercase",
          backgroundColor: "#F8FAFC",
          textColor: "#111827",
          hoverColor: "#E2E8F0",
          borderColor: "#E2E8F0",
          height: 38,
          topPadding: 8,
          bottomPadding: 8,
          dividerIcon: "|",
          dividerColor: "#94A3B8",
          hasCta: false,
        }),
      },
    ];

    for (const b of sampleBanners) {
      await prisma.banner.create({
        data: {
          shopDomain,
          ...b,
        },
      });
    }

    banners = await prisma.banner.findMany({
      where: { shopDomain },
      orderBy: { updatedAt: "desc" },
    });
  }

  return banners;
}

export async function getStoreSettings(shopDomain) {
  let settings = await prisma.storeSettings.findUnique({
    where: { shopDomain },
  });

  if (!settings) {
    settings = await prisma.storeSettings.create({
      data: {
        shopDomain,
        defaultAnimation: "Right to Left",
        defaultSpeed: "Normal",
        defaultHeight: 40,
        defaultBgColor: "#19D8CF",
        defaultTextColor: "#111827",
        defaultHoverColor: "#06B6D4",
        reduceMotion: false,
        pauseOnHover: true,
        pauseOnFocus: true,
      },
    });
  }

  return settings;
}
